"""Reusable scientific operations for the EEG motor-imagery project."""

from .preprocessing import (
    FilterSettings,
    PreprocessedRecording,
    PreprocessingConfig,
    apply_analysis_reference,
    apply_production_filter,
    design_production_filter,
    load_preprocessing_config,
    load_valid_recording,
    preprocess_recording,
)
from .epoching import (
    EpochingConfig,
    EpochRecord,
    RunEpochs,
    calculate_trial_quality,
    extract_run_epochs,
    load_epoching_config,
    semantic_mapping_for_run,
)
from .time_frequency import (
    EventRelatedSpectralConfig,
    FrequencyBand,
    SpectralEpochDataset,
    TimeFrequencyPower,
    TrialPair,
    assemble_spectral_epoch_dataset,
    compute_morlet_power,
    load_event_related_spectral_config,
    normalize_task_tfr_percent,
    pair_task_with_preceding_rest,
    percent_power_change,
    trial_band_measurements,
)

__all__ = [
    "FilterSettings",
    "PreprocessedRecording",
    "PreprocessingConfig",
    "apply_analysis_reference",
    "apply_production_filter",
    "design_production_filter",
    "load_preprocessing_config",
    "load_valid_recording",
    "preprocess_recording",
    "EpochingConfig",
    "EpochRecord",
    "RunEpochs",
    "calculate_trial_quality",
    "extract_run_epochs",
    "load_epoching_config",
    "semantic_mapping_for_run",
    "EventRelatedSpectralConfig",
    "FrequencyBand",
    "SpectralEpochDataset",
    "TimeFrequencyPower",
    "TrialPair",
    "assemble_spectral_epoch_dataset",
    "compute_morlet_power",
    "load_event_related_spectral_config",
    "normalize_task_tfr_percent",
    "pair_task_with_preceding_rest",
    "percent_power_change",
    "trial_band_measurements",
]
